---
apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: imageuseslatesttag
  spec:
    template:
      spec:
        containers:
          - name: pastry
            image: quay.io/microcks/quarkus-api-pastry:latest